version: '3'
services:
  selenium_service:
    image: selenium/standalone-chrome
    container_name: container_selenium
    environment:
      VNC_NO_PASSWORD: 1
    shm_size: 2gb
    ports:
      - 4444:4444

